% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Nov-2020 10:59:31
%  MATLAB version: 9.6.0.1072779 (R2019a)
% -------------------------------------------------------------------
saveVarsMat = load('STEW_90corss140.mat');

ans = saveVarsMat.ans; % <90x140 double> too many elements

clear saveVarsMat;
